---
title: "Final Join"
author: "Miguel Angel Armengol de la Hoz"
date: "August 1, 2018"
output: html_document
---

# Environment

```{r}
library(RPostgreSQL)
library(DBI)
library(dplyr)
library(summarytools)
```

## Data join

### Final Dataset
```{r}

#Demographics joins
final_dataset<-left_join(cmo_and_extubation_and_death_24, extubated_procedureevents_mv[, c('subject_id','extubated_in_procedureevents')])
final_dataset<-left_join(final_dataset, demographics_all)
final_dataset<-left_join(final_dataset, gcs_last_day)
final_dataset<-left_join(final_dataset, vent_mode_last_pre_ext_final)
final_dataset<-left_join(final_dataset, top15icd9_codes_with_labels_sumarized)
final_dataset<-left_join(final_dataset,last_pao2fio2_patients_final)

#Epochs joins
final_dataset<-left_join(final_dataset,final_rr_te_epoch)
final_dataset<-left_join(final_dataset,rr_from_patients_tofilter_first_final)
final_dataset<-left_join(final_dataset,cohort_with_opioids_infusion_epoch)
final_dataset<-left_join(final_dataset,cohort_with_benzodiazepines_infusion_epoch)
final_dataset<-left_join(final_dataset,cohort_with_opioids_bolus_epoch)
final_dataset<-left_join(final_dataset,cohort_with_benzodiazepines_bolus_epoch)
final_dataset<-left_join(final_dataset,cohort_with_opioids_infusion_neg_epoch)
final_dataset<-left_join(final_dataset,cohort_with_benzodiazepines_infusion_neg_epoch)
final_dataset<-left_join(final_dataset,cohort_with_opioids_bolus_neg_epoch)
final_dataset<-left_join(final_dataset,cohort_with_benzodiazepines_bolus_neg_epoch)
final_dataset<-left_join(final_dataset,cohort_with_re_epoch)
final_dataset<-left_join(final_dataset,cohort_with_ps_epoch)
final_dataset<-left_join(final_dataset,cohort_with_min_rass_epoch)
final_dataset<-left_join(final_dataset,cohort_with_max_rass_epoch)

#new drugs Epochs joins
final_dataset<-left_join(final_dataset,cohort_with_propofol_bolus_epoch)
final_dataset<-left_join(final_dataset,cohort_with_diazepam_bolus_epoch)
final_dataset<-left_join(final_dataset,cohort_with_midazolam_bolus_epoch)
final_dataset<-left_join(final_dataset,cohort_with_lorazepam_bolus_epoch)
final_dataset<-left_join(final_dataset,cohort_with_dexmedetomedie_bolus_epoch)

final_dataset<-left_join(final_dataset,cohort_with_propofol_infusion_epoch)
final_dataset<-left_join(final_dataset,cohort_with_diazepam_infusion_epoch)
final_dataset<-left_join(final_dataset,cohort_with_midazolam_infusion_epoch)
final_dataset<-left_join(final_dataset,cohort_with_lorazepam_infusion_epoch)
final_dataset<-left_join(final_dataset,cohort_with_dexmedetomedie_infusion_epoch)

#new drugs neg Epochs joins
final_dataset<-left_join(final_dataset,cohort_with_propofol_bolus_neg_epoch)
final_dataset<-left_join(final_dataset,cohort_with_diazepam_bolus_neg_epoch)
final_dataset<-left_join(final_dataset,cohort_with_midazolam_bolus_neg_epoch)
final_dataset<-left_join(final_dataset,cohort_with_lorazepam_bolus_neg_epoch)
final_dataset<-left_join(final_dataset,cohort_with_dexmedetomedie_bolus_neg_epoch)

final_dataset<-left_join(final_dataset,cohort_with_propofol_infusion_neg_epoch)
final_dataset<-left_join(final_dataset,cohort_with_diazepam_infusion_neg_epoch)
final_dataset<-left_join(final_dataset,cohort_with_midazolam_infusion_neg_epoch)
final_dataset<-left_join(final_dataset,cohort_with_lorazepam_infusion_neg_epoch)
final_dataset<-left_join(final_dataset,cohort_with_dexmedetomedie_infusion_neg_epoch)


#new drugs with only neg infusions Epochs joins
final_dataset<-left_join(final_dataset,cohort_with_phenylephrine_infusion_neg_epoch)
final_dataset<-left_join(final_dataset,cohort_with_norepinephrine_infusion_neg_epoch)
final_dataset<-left_join(final_dataset,cohort_with_dopamine_infusion_neg_epoch)
final_dataset<-left_join(final_dataset,cohort_with_epinephrine_infusion_neg_epoch)
final_dataset<-left_join(final_dataset,cohort_with_vasopressin_infusion_neg_epoch)                       


library(foreign)
write.dta(final_dataset, "final_dataset.dta")
cat(names(final_dataset),sep = '\n')
#view(dfSummary(final_dataset))
```

# Variables distribution

```{r}
view(dfSummary(final_dataset%>%select(
propofol_bolus_epoch_01,
propofol_bolus_epoch_02,
diazepam_bolus_epoch_01,
diazepam_bolus_epoch_02,
midazolam_bolus_epoch_01,
midazolam_bolus_epoch_02,
lorazepam_bolus_epoch_01,
lorazepam_bolus_epoch_02,
dexmedetomedie_bolus_epoch_01,
dexmedetomedie_bolus_epoch_02,
propofol_infusion_epoch_01,
propofol_infusion_epoch_02,
diazepam_infusion_epoch_01,
diazepam_infusion_epoch_02,
midazolam_infusion_epoch_01,
midazolam_infusion_epoch_02,
lorazepam_infusion_epoch_01,
lorazepam_infusion_epoch_02,
dexmedetomedie_infusion_epoch_01,
dexmedetomedie_infusion_epoch_02,
propofol_bolus_neg_epoch_01,
propofol_bolus_neg_epoch_02,
diazepam_bolus_neg_epoch_01,
diazepam_bolus_neg_epoch_02,
midazolam_bolus_neg_epoch_01,
midazolam_bolus_neg_epoch_02,
lorazepam_bolus_neg_epoch_01,
lorazepam_bolus_neg_epoch_02,
dexmedetomedie_bolus_neg_epoch_01,
dexmedetomedie_bolus_neg_epoch_02,
propofol_infusion_neg_epoch_01,
propofol_infusion_neg_epoch_02,
diazepam_infusion_neg_epoch_01,
diazepam_infusion_neg_epoch_02,
midazolam_infusion_neg_epoch_01,
midazolam_infusion_neg_epoch_02,
lorazepam_infusion_neg_epoch_01,
lorazepam_infusion_neg_epoch_02,
dexmedetomedie_infusion_neg_epoch_01,
dexmedetomedie_infusion_neg_epoch_02,
phenylephrine_infusion_neg_epoch_01,
phenylephrine_infusion_neg_epoch_02,
norepinephrine_infusion_neg_epoch_01,
norepinephrine_infusion_neg_epoch_02,
dopamine_infusion_neg_epoch_01,
dopamine_infusion_neg_epoch_02,
epinephrine_infusion_neg_epoch_01,
epinephrine_infusion_neg_epoch_02,
vasopressin_infusion_neg_epoch_01,
vasopressin_infusion_neg_epoch_02
)))
```



